# Generated by Django 3.2.4 on 2021-10-03 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=40)),
                ('cpic', models.ImageField(default='', upload_to='static/category/')),
                ('cdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=200)),
                ('cpic', models.ImageField(default='', upload_to='static/courses/')),
                ('cfee', models.CharField(max_length=100)),
                ('cdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdes', models.CharField(max_length=200)),
                ('gpic', models.ImageField(default='', upload_to='static/gallery/')),
                ('gdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='recuiters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=200)),
                ('rpic', models.ImageField(default='', upload_to='static/recuiters/')),
                ('rdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=80, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=100)),
                ('ppic', models.ImageField(default='', upload_to='static/profile/')),
                ('address', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='placements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=80)),
                ('cmpname', models.CharField(max_length=80)),
                ('cmplogo', models.ImageField(default='', upload_to='static/placements/')),
                ('city', models.CharField(max_length=100)),
                ('pyear', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('stupic', models.ImageField(default='', upload_to='static/studentpic/')),
                ('pdate', models.DateField()),
                ('pcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.courses')),
            ],
        ),
    ]
